version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: nila2003
      POSTGRES_PASSWORD: bornNila24*4
      POSTGRES_DB: nila_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
